
services:
  # ----------------- Kafka Broker (Redpanda) -----------------
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "1G"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"

  # ----------------- Collector API -----------------
  collector-api:
    build:
      context: .
      dockerfile: docker.api
    container_name: collector-api
    depends_on:
      - redpanda
    environment:
      KAFKA_BROKER: redpanda:9092
      TELEMETRY_TOPIC: metrics-topic
    ports:
      - "8080:8080"

  # ----------------- Consumers -----------------
  consumer-audit:
    build:
      context: .
      dockerfile: docker.consumer
    container_name: consumer-audit
    depends_on:
      - redpanda
    environment:
      KAFKA_BROKER: redpanda:9092
      TOPIC: audit-topic

  consumer-alarm:
    build:
      context: .
      dockerfile: docker.consumer
    container_name: consumer-alarm
    depends_on:
      - redpanda
    environment:
      KAFKA_BROKER: redpanda:9092
      TOPIC: alarm-topic

  consumer-metrics:
    build:
      context: .
      dockerfile: docker.consumer
    container_name: consumer-metrics
    depends_on:
      - redpanda
    environment:
      KAFKA_BROKER: redpanda:9092
      TOPIC: metrics-topic
